Header header
# TimeDistance mTimeDistance;
applanix/TimeDistanceMsg TimeDistance
# /// Latitude
float64 Latitude
# /// Longitude
float64 Longitude
# /// Altitude
float64 Altitude
# /// North velocity
float32 NorthVelocity
# /// East velocity
float32 EastVelocity
# /// Down velocity
float32 DownVelocity
# /// Roll
float64 Roll
# /// Pitch
float64 Pitch
# /// Heading
float64 Heading
# /// Wander angel
float64 WanderAngle
# /// Track angle
float32 TrackAngle
# /// Speed
float32 Speed
# /// Angular rate longitude
float32 AngularRateLong
# /// Angular rate transverse
float32 AngularRateTrans
# /// Angular rate down
float32 AngularRateDown
# /// Acceleration longitude
float32 AccLong
# /// Acceleration transverse
float32 AccTrans
# /// Acceleration down
float32 AccDown
# /// Alignment status
uint8 AlignementStatus
