Header header
# /// Time/Distance field
# TimeDistance mTimeDistance
poslv/TimeDistanceMsg TimeDistance
# /// North position RMS error
float32 NorthPositionRMSError
# /// East position RMS error
float32 EastPositionRMSError
# /// Down position RMS error
float32 DownPositionRMSError
# /// North velocity RMS error
float32 NorthVelocityRMSError
# /// East velocity RMS error
float32 EastVelocityRMSError
# /// Down velocity RMS error
float32 DownVelocityRMSError
# /// Roll RMS error
float32 RollRMSError
# /// Pitch RMS error
float32 PitchRMSError
# /// Heading RMS error
float32 HeadingRMSError
# /// Error ellipsoid semi major
float32 ErrorEllipsoidSemiMajor
# /// Error ellipsoid semi minor
float32 ErrorEllipsoidSemiMinor
# /// Error ellipsoid orientation
float32 ErrorEllipsoidOrientation
